### PR TITLE
Quote resource names to to emit valid PCL

### LINKED ISSUE #3: Unable to handle objects that contain a `.` in their name
### What happened?

Any Kubernetes object that contains a `.` in their name will result in a conversion error. While Kubernetes recommends using DNS labels for names, using a dot is not strictly prohibited. Our converter fails as the intermediary PCL to target language fails with `Either a quoted string block label or an opening brace ("{") is expected here.`

We will need to sanitize the object name to ensure generation succeeds.

### Example

A valid pod resource:

```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: frontend
  name: nginx.pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14-alpine
      resources:
        limits:
          memory: 20Mi
          cpu: 0.2
```

### Output of `pulumi about`

-

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
### Description

Fixes #3 by quoting resource names and letting program-gen handle their normalization. 

Added a new example to the integration tests directory called "name_with_dot" to test this use case then regenerated the examples based on latest kuberneters provider v4.7.1 which is why you see the diffs. 

Note: bumped the version from 0.1.0 to 0.2.0 so merging will trigger a release (I can remove this if you want to trigger a release in a separate PR/branch)

### CODE REVIEW

File: src/Converter/Printer.fs [hunk 1]
```diff
@@ -149,7 +149,7 @@ let printProgram(program: PulumiProgram) =
             append "}\n"
 
         | PulumiNode.Resource resource ->
-            append $"resource {resource.name} \"{resource.token}\" {{\n"
+            append $"resource \"{resource.name}\" \"{resource.token}\" {{\n"
```
Comment (Zaid-Ajaj) [inline src/Converter/Printer.fs:152]: The actual fix here ☝️

**Review by rquitales — APPROVED** [review]
